global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "couchbase"
    basic_auth:
      username: "Administrator"
      password: "TU_PASSWORD_AQUI"
    static_configs:
      - targets: ["localhost:8091"]
